blank_issues_enabled: false
contact_links:
  - name: CONTRIBUTING.md
    url: https://github.com/sebastian-altamirano/json-file-handler/blob/master/CONTRIBUTING.md
    about: Please read the contribution guidelines before submitting
